# Generated by Django 3.1.6 on 2021-02-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_auto_20210219_1609'),
        ('training', '0002_auto_20210219_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Seminargruppe',
                'verbose_name_plural': 'Seminargruppen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeminarTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('short_description', models.TextField(verbose_name='Kurzbeschreibung')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('image', models.ImageField(upload_to='seminartopic/', verbose_name='Bild')),
                ('certificate', models.TextField(verbose_name='Zertifikatsaussage')),
                ('languages', models.TextField(verbose_name='Sprachen')),
                ('executions', models.TextField(verbose_name='Durchführung')),
                ('seminar_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seminar_topics', to='training.seminargroup', verbose_name='Seminargruppe')),
            ],
            options={
                'verbose_name': 'Seminarthema',
                'verbose_name_plural': 'Seminarthemen',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SeminarExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titel')),
                ('short_description', models.TextField(verbose_name='Kurzbeschreibung')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Enddatum')),
                ('location', models.CharField(max_length=50, verbose_name='Ort')),
                ('language', models.CharField(max_length=50, verbose_name='Sprache')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('execution_hours', models.TextField(verbose_name='Durchführungszeiten')),
                ('members', models.ManyToManyField(blank=True, to='team.Member', verbose_name='Teammitglieder')),
            ],
            options={
                'verbose_name': 'Kursdurchführung',
                'verbose_name_plural': 'Kursdurchführungen',
                'ordering': ['title'],
            },
        ),
    ]
