# Generated by Django 3.1.6 on 2021-02-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_seminarexecution_seminargroup_seminartopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarexecution',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preis'),
        ),
    ]
