# Generated by Django 3.1.6 on 2021-02-19 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20210219_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarexecution',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminarexecution',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seminarexecution',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seminargroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminargroup',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seminargroup',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seminartopic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminartopic',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seminartopic',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
