# Generated by Django 3.1.6 on 2021-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20210224_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarexecution',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Entwurf'),
        ),
        migrations.AlterField(
            model_name='seminargroup',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Entwurf'),
        ),
        migrations.AlterField(
            model_name='seminartopic',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Entwurf'),
        ),
    ]
