# Generated by Django 3.1.6 on 2021-02-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_seminargroup_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminartopic',
            name='slug',
            field=models.SlugField(default='', help_text='Erscheint in der URL. Zum Beispiel: cocoo.de/seminarthema/certified-less-practitioner/.', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminargroup',
            name='slug',
            field=models.SlugField(help_text='Erscheint in der URL. Zum Beispiel: cocoo.de/seminargruppe/scrum/.', unique=True, verbose_name='Slug'),
        ),
    ]
