# Generated by Django 3.1.6 on 2021-03-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_member_short_description'),
        ('training', '0010_auto_20210226_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminartopic',
            name='trainers',
            field=models.ManyToManyField(blank=True, to='team.Member', verbose_name='Trainer'),
        ),
        migrations.AlterField(
            model_name='seminartopic',
            name='executions',
            field=models.TextField(verbose_name='Durchführungen'),
        ),
    ]
