# Generated by Django 3.1.6 on 2021-03-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_auto_20210301_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminarexecution',
            options={'ordering': ['start_date'], 'verbose_name': 'Seminardurchführung', 'verbose_name_plural': 'Seminardurchführungen'},
        ),
        migrations.RemoveField(
            model_name='seminarexecution',
            name='description',
        ),
        migrations.RemoveField(
            model_name='seminarexecution',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='seminarexecution',
            name='title',
        ),
        migrations.AddField(
            model_name='seminarexecution',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Noch Plätze verfügbar'), ('ALMOST_FULL', 'Wenige Plätze verfügbar'), ('FULL', 'Ausgebucht')], default=None, max_length=50, verbose_name='Buchungsstatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminarexecution',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='training.seminartopic', verbose_name='Thema'),
            preserve_default=False,
        ),
    ]
