# Generated by Django 3.1.6 on 2021-03-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_auto_20210302_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarexecution',
            name='execution',
            field=models.CharField(choices=[('PRESENCE', 'Präsenz'), ('VIRTUAL', 'Virtuell')], default='', max_length=40, verbose_name='Durchführung'),
            preserve_default=False,
        ),
    ]
