# Generated by Django 3.1.6 on 2021-03-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_seminarexecution_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarexecution',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ort'),
        ),
    ]
