# Generated by Django 3.1.6 on 2021-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_auto_20210318_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarexecution',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='seminartopic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seminartopic/', verbose_name='Bild'),
        ),
    ]
