# Generated by Django 3.1.6 on 2021-03-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_auto_20210330_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarexecution',
            name='show_on_index',
            field=models.BooleanField(default=True, verbose_name='Auf der Startseite im Slider anzeigen'),
        ),
    ]
