# Generated by Django 3.1.6 on 2021-04-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_auto_20210416_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminarexecution',
            options={'ordering': ['start_date'], 'verbose_name': 'Seminardurchführung', 'verbose_name_plural': 'Seminardurchführungen'},
        ),
    ]
