# Generated by Django 3.1.6 on 2021-04-30 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_image'),
        ('training', '0021_remove_seminartopic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminartopic',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.image', verbose_name='Bild'),
        ),
    ]
