# Generated by Django 3.2.3 on 2021-05-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_seminartopic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminartopic',
            name='promotions',
            field=models.TextField(default='', verbose_name='Rabattaktionen'),
            preserve_default=False,
        ),
    ]
