# Generated by Django 3.2.3 on 2021-05-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_seminartopic_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarexecution',
            name='early_booking_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Frühbucherpreis'),
        ),
        migrations.AddField(
            model_name='seminarexecution',
            name='show_early_booking_price',
            field=models.BooleanField(default=False, verbose_name='Frühbucherpreis anzeigen'),
            preserve_default=False,
        ),
    ]
