# Generated by Django 3.2.3 on 2021-05-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_auto_20210517_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarexecution',
            name='early_booking_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Frühbucherpreis'),
        ),
    ]
