# Generated by Django 3.2.3 on 2021-05-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_alter_seminarexecution_early_booking_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminargroup',
            options={'ordering': ['slug'], 'verbose_name': 'Seminargruppe', 'verbose_name_plural': 'Seminargruppen'},
        ),
        migrations.AlterModelOptions(
            name='seminartopic',
            options={'ordering': ['slug'], 'verbose_name': 'Seminarthema', 'verbose_name_plural': 'Seminarthemen'},
        ),
    ]
