# Generated by Django 3.2.3 on 2021-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_auto_20210517_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminartopic',
            name='promotions',
            field=models.TextField(blank=True, verbose_name='Rabattaktionen'),
        ),
    ]
