# Generated by Django 3.2.3 on 2022-05-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_alter_seminartopic_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarexecution',
            name='price_text',
            field=models.CharField(blank=True, help_text='Zum Beispiel: inkl. MwSt.', max_length=100, verbose_name='Text nach dem Preis'),
        ),
    ]
