# Generated by Django 3.1.6 on 2021-04-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='CoCoo GmbH', max_length=100, verbose_name='Unternehmensname')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='E-Mail')),
                ('address_street', models.CharField(blank=True, max_length=100, verbose_name='Adresse Straße')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='Adresse Stadt')),
                ('help_statement', models.TextField(blank=True, verbose_name='Statement')),
            ],
            options={
                'verbose_name': 'Allgemein',
            },
        ),
    ]
