# Generated by Django 4.2.19 on 2025-02-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="general",
            name="default_from_email",
            field=models.CharField(
                blank=True,
                default="info@example.com",
                max_length=255,
                verbose_name="Absenderadresse (FROM)",
            ),
        ),
        migrations.AddField(
            model_name="general",
            name="smtp_host",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="general",
            name="smtp_password",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="general",
            name="smtp_port",
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name="general",
            name="smtp_use_ssl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="general",
            name="smtp_use_tls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="general",
            name="smtp_user",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
