# Generated by Django 4.2.19 on 2025-02-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_general_default_from_email_general_smtp_host_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="general",
            old_name="smtp_host",
            new_name="email_host",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="smtp_password",
            new_name="email_host_password",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="smtp_user",
            new_name="email_host_user",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="smtp_port",
            new_name="email_port",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="smtp_use_ssl",
            new_name="email_use_ssl",
        ),
        migrations.RenameField(
            model_name="general",
            old_name="smtp_use_tls",
            new_name="email_use_tls",
        ),
    ]
