# Generated by Django 4.2.19 on 2025-02-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_rename_smtp_host_general_email_host_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="general",
            name="email_use_ssl",
        ),
    ]
