# Generated by Django 3.1.6 on 2021-03-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_contact_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='form_successheading',
            field=models.CharField(default='', max_length=100, verbose_name='Formular Abgeschickt Überschrift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='form_successlink',
            field=models.CharField(default='', max_length=80, verbose_name='Formular Abgeschickt Linktext'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='form_successtext',
            field=models.CharField(default='', max_length=300, verbose_name='Formular Abgeschickt Text'),
            preserve_default=False,
        ),
    ]
