# Generated by Django 3.1.6 on 2021-04-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_auto_20210401_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_heading',
            field=models.CharField(default='Unser Team', max_length=100, verbose_name='Team Überschrift'),
            preserve_default=False,
        ),
    ]
