# Generated by Django 3.1.6 on 2021-04-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_auto_20210401_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='help_statement',
            field=models.TextField(default='', verbose_name='Statement'),
            preserve_default=False,
        ),
    ]
