# Generated by Django 3.1.6 on 2021-04-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_general_help_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='help_statement',
            field=models.TextField(blank=True, verbose_name='Statement'),
        ),
    ]
