# Generated by Django 3.1.6 on 2021-04-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_seminar'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='form_successbutton',
            field=models.CharField(default='', max_length=80, verbose_name='Formular Erfolg Button'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='form_successtext',
            field=models.TextField(default='', verbose_name='Formular Erfolg Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='form_successtitle',
            field=models.CharField(default='', max_length=80, verbose_name='Formular Erfolg Titel'),
            preserve_default=False,
        ),
    ]
