# Generated by Django 3.1.6 on 2021-02-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='certifications',
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(null=True, upload_to='certification/', verbose_name='Bild')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.member', verbose_name='Teammitglied')),
            ],
            options={
                'verbose_name': 'Zertifikat',
                'verbose_name_plural': 'Zertifikate',
                'ordering': ['member'],
            },
        ),
    ]
