# Generated by Django 3.1.6 on 2021-02-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210219_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Mitarbeiter', 'verbose_name_plural': 'Mitarbeiter'},
        ),
    ]
