# Generated by Django 3.1.6 on 2021-02-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20210219_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='certification/', verbose_name='Bild'),
            preserve_default=False,
        ),
    ]
