# Generated by Django 3.1.6 on 2021-03-01 18:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_member_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Beschreibung'),
        ),
    ]
