# Generated by Django 3.1.6 on 2021-03-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20210301_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Mitarbeiter', 'verbose_name_plural': 'Mitarbeiter'},
        ),
    ]
