# Generated by Django 3.1.6 on 2021-03-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20210301_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(default='', help_text='Erscheint in der URL. Zum Beispiel: cocoo.de/seminargruppe/scrum/.', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
