# Generated by Django 3.1.6 on 2021-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_auto_20210301_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Bild')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Buch',
                'verbose_name_plural': 'Bücher',
                'ordering': ['title'],
            },
        ),
    ]
