# Generated by Django 3.1.6 on 2021-04-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_auto_20210411_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='members',
            field=models.ManyToManyField(to='team.Member', verbose_name='Teammitglieder'),
        ),
    ]
