# Generated by Django 3.1.6 on 2021-04-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_certification_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='members',
            field=models.ManyToManyField(related_name='certifications', to='team.Member', verbose_name='Teammitglieder'),
        ),
    ]
