# Generated by Django 3.1.6 on 2021-04-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_auto_20210411_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='image',
        ),
    ]
