# Generated by Django 3.2.3 on 2021-06-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_certification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Entwurf'),
        ),
    ]
