# Generated by Django 3.2.3 on 2021-06-17 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_image'),
        ('team', '0019_book_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='new_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.image', verbose_name='Neues Bild'),
        ),
    ]
