# Generated by Django 3.2.3 on 2021-06-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_member_new_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='image',
            new_name='old_image',
        ),
    ]
