# Generated by Django 3.1.6 on 2021-03-01 19:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210219_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprotection',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='imprint',
            name='heading',
        ),
        migrations.AlterField(
            model_name='dataprotection',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='imprint',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Inhalt'),
        ),
    ]
