# Generated by Django 3.1.6 on 2021-03-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210318_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='header_text',
            field=models.CharField(max_length=200, verbose_name='Header Text'),
        ),
    ]
