# Generated by Django 3.1.6 on 2021-03-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210318_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='header_image',
            field=models.ImageField(default='', upload_to='contact/', verbose_name='Header Bild'),
            preserve_default=False,
        ),
    ]
