# Generated by Django 3.1.6 on 2021-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210319_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='company_name',
            field=models.CharField(default='CoCoo GmbH', max_length=100, verbose_name='Unternehmensname'),
        ),
    ]
