# Generated by Django 3.1.6 on 2021-04-01 13:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_general_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_heading', models.CharField(max_length=60, verbose_name='Header Überschrift')),
                ('header_text', models.CharField(max_length=200, verbose_name='Header Text')),
                ('header_text_red', models.CharField(max_length=200, verbose_name='Header Text Rot')),
                ('header_image', models.ImageField(upload_to='index/', verbose_name='Header Bild')),
                ('header_buttonleft', models.CharField(max_length=50, verbose_name='Header Button Links')),
                ('header_buttonright', models.CharField(max_length=50, verbose_name='Header Button Rechts')),
                ('intro_pretitle', models.CharField(max_length=200, verbose_name='Intro Vorüberschrift')),
                ('intro_title', models.CharField(max_length=200, verbose_name='Intro Überschrift')),
                ('intro_subtitle', models.CharField(max_length=200, verbose_name='Intro Unterüberschrift')),
                ('intro_leftheading', models.CharField(max_length=200, verbose_name='Intro Überschrift Links')),
                ('intro_lefttext', models.TextField(verbose_name='Intro Text Links')),
                ('intro_leftbutton', models.CharField(max_length=200, verbose_name='Intro Button Links')),
                ('intro_rightheading', models.CharField(max_length=200, verbose_name='Intro Überschrift Rechts')),
                ('intro_righttext', models.TextField(verbose_name='Intro Text Rechts')),
                ('intro_rightbutton', models.CharField(max_length=200, verbose_name='Intro Button Rechts')),
                ('seminars_heading', models.CharField(max_length=100, verbose_name='Seminare Überschrift')),
                ('testimonials_heading', models.CharField(max_length=100, verbose_name='Referenzen Überschrift')),
            ],
            options={
                'verbose_name': 'Startseite',
            },
        ),
        migrations.CreateModel(
            name='SeminarTopicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_heading', models.CharField(max_length=60, verbose_name='Header Überschrift')),
                ('header_text', models.CharField(max_length=200, verbose_name='Header Text')),
                ('header_image', models.ImageField(upload_to='seminartopiclist/', verbose_name='Header Bild')),
            ],
            options={
                'verbose_name': 'Seminare',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_heading', models.CharField(max_length=60, verbose_name='Header Überschrift')),
                ('header_text', models.CharField(max_length=200, verbose_name='Header Text')),
                ('header_image', models.ImageField(upload_to='team/', verbose_name='Header Bild')),
                ('about_heading', models.CharField(max_length=100, verbose_name='Über uns Überschrift')),
                ('about_text', tinymce.models.HTMLField(verbose_name='Über uns Text')),
                ('books_heading', models.CharField(max_length=100, verbose_name='Bücher Überschrift')),
                ('books_subheading', models.CharField(max_length=200, verbose_name='Bücher Unterüberschrift')),
            ],
            options={
                'verbose_name': 'Team',
            },
        ),
    ]
