# Generated by Django 3.1.6 on 2021-04-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_team_team_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='header_text_red',
            new_name='header_headingred',
        ),
    ]
