# Generated by Django 3.1.6 on 2021-04-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210401_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='header_headingred',
            field=models.CharField(max_length=200, verbose_name='Header Überschrift Rot'),
        ),
    ]
