# Generated by Django 3.1.6 on 2021-04-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20210416_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_pretitle', models.CharField(max_length=80, verbose_name='Inhalt Vortitel')),
                ('content_title', models.CharField(max_length=80, verbose_name='Inhalt Titel')),
            ],
            options={
                'verbose_name': 'Teammitglied',
            },
        ),
    ]
