# Generated by Django 3.1.6 on 2021-04-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20210423_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='General',
        ),
    ]
