# Generated by Django 3.1.6 on 2021-04-30 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_image'),
        ('pages', '0028_auto_20210430_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaching',
            name='header_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='settings.image', verbose_name='Header Bild'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='header_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='settings.image', verbose_name='Header Bild'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='header_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='settings.image', verbose_name='Header Bild'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminars',
            name='header_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='settings.image', verbose_name='Header Bild'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='header_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='settings.image', verbose_name='Header Bild'),
            preserve_default=False,
        ),
    ]
