# Generated by Django 3.1.6 on 2021-04-30 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_image'),
        ('pages', '0029_auto_20210430_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaching',
            name='content_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coaching_content_image', to='settings.image', verbose_name='Inhalt Bild'),
        ),
        migrations.AlterField(
            model_name='coaching',
            name='header_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coaching_header_image', to='settings.image', verbose_name='Header Bild'),
        ),
    ]
