# Generated by Django 3.2.3 on 2021-05-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20210430_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='infos_subtitle4',
            field=models.CharField(blank=True, max_length=80, verbose_name='Rabattaktionen Titel'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='infos_subtitle1',
            field=models.CharField(blank=True, max_length=80, verbose_name='Zertifikat Titel'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='infos_subtitle2',
            field=models.CharField(blank=True, max_length=80, verbose_name='Sprache Titel'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='infos_subtitle3',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ort Titel'),
        ),
    ]
