# Generated by Django 3.2.3 on 2021-05-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_seminar_seminars_empty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Detail: Teammitglied'},
        ),
        migrations.AlterModelOptions(
            name='seminar',
            options={'verbose_name': 'Detail: Seminar'},
        ),
    ]
