# Generated by Django 3.2.3 on 2021-05-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20210517_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coaching',
            options={'verbose_name': 'A: Coaching'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'A: Kontakt'},
        ),
        migrations.AlterModelOptions(
            name='dataprotection',
            options={'verbose_name': 'C: Datenschutz'},
        ),
        migrations.AlterModelOptions(
            name='imprint',
            options={'verbose_name': 'C: Impressum'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'A: Startseite'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'B: Teammitglied'},
        ),
        migrations.AlterModelOptions(
            name='seminar',
            options={'verbose_name': 'B: Seminar'},
        ),
        migrations.AlterModelOptions(
            name='seminars',
            options={'verbose_name': 'A: Seminare'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'A: Team'},
        ),
    ]
