# Generated by Django 3.2.3 on 2021-05-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20210517_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='seminars_earlybooking',
            field=models.CharField(blank=True, max_length=80, verbose_name='Frühbucherpreis Text'),
        ),
    ]
