# Generated by Django 3.2.3 on 2021-05-31 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_seminar_seminars_earlybooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='form_dataprotectiontext',
            new_name='form_dataprotection',
        ),
    ]
