# Generated by Django 3.2.3 on 2021-05-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_rename_form_dataprotectiontext_contact_form_dataprotection'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='seminars_autoplay',
            field=models.IntegerField(default=5000, help_text='Die Einheit ist [ms]. 5000 entspricht 5 Sekunden.', verbose_name='Seminare Autplay Timer'),
        ),
    ]
