# Generated by Django 3.2.3 on 2021-06-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_index_testimonials_autoplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaching',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Beschreibung'),
        ),
        migrations.AddField(
            model_name='coaching',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Titel'),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Beschreibung'),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Titel'),
        ),
        migrations.AddField(
            model_name='dataprotection',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Beschreibung'),
        ),
        migrations.AddField(
            model_name='dataprotection',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Titel'),
        ),
        migrations.AddField(
            model_name='imprint',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Beschreibung'),
        ),
        migrations.AddField(
            model_name='imprint',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Titel'),
        ),
        migrations.AddField(
            model_name='index',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Beschreibung'),
        ),
        migrations.AddField(
            model_name='index',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Titel'),
        ),
        migrations.AddField(
            model_name='member',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Beschreibung'),
        ),
        migrations.AddField(
            model_name='member',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Titel'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Beschreibung'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Titel'),
        ),
        migrations.AddField(
            model_name='seminars',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Beschreibung'),
        ),
        migrations.AddField(
            model_name='seminars',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Titel'),
        ),
        migrations.AddField(
            model_name='team',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Beschreibung'),
        ),
        migrations.AddField(
            model_name='team',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Titel'),
        ),
    ]
