# Generated by Django 3.2.3 on 2021-06-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_auto_20210610_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='member',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='meta_title',
        ),
    ]
