# Generated by Django 3.2.3 on 2021-06-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_auto_20210617_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='seminars_few_places',
            field=models.CharField(blank=True, default='Wenige Plätze verfügbar', max_length=80, verbose_name='Seminare: Wenige Plätze verfügbar'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='content_pretitle',
            field=models.CharField(blank=True, max_length=80, verbose_name='Inhalt: Vortitel'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='content_title',
            field=models.CharField(blank=True, max_length=80, verbose_name='Inhalt: Titel'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='form_button',
            field=models.CharField(blank=True, max_length=200, verbose_name='Formular: Button'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='form_dataprotection',
            field=models.CharField(blank=True, max_length=200, verbose_name='Formular: Datenschutz Text'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='form_requiredfields',
            field=models.CharField(blank=True, max_length=200, verbose_name='Formular: Muss Felder Text'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='form_successbutton',
            field=models.CharField(blank=True, max_length=80, verbose_name='Formular: Erfolg Button'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='form_successtext',
            field=models.TextField(verbose_name='Formular: Erfolg Text'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='form_successtitle',
            field=models.CharField(blank=True, max_length=80, verbose_name='Formular: Erfolg Titel'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='form_text',
            field=models.CharField(blank=True, max_length=140, verbose_name='Formular: Text'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='form_title',
            field=models.CharField(blank=True, max_length=80, verbose_name='Formular: Titel'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='infos_subtitle1',
            field=models.CharField(blank=True, max_length=80, verbose_name='Infos: Zertifikat Titel'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='infos_subtitle2',
            field=models.CharField(blank=True, max_length=80, verbose_name='Infos: Sprache Titel'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='infos_subtitle3',
            field=models.CharField(blank=True, max_length=80, verbose_name='Infos: Ort Titel'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='infos_subtitle4',
            field=models.CharField(blank=True, max_length=80, verbose_name='Infos: Rabattaktionen Titel'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='infos_title',
            field=models.CharField(blank=True, max_length=80, verbose_name='Infos: Titel'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminars_earlybooking',
            field=models.CharField(blank=True, max_length=80, verbose_name='Seminare: Frühbucherpreis Text'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminars_empty',
            field=models.TextField(blank=True, verbose_name='Seminare: Keine Seminare vorhanden'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminars_title',
            field=models.CharField(blank=True, max_length=80, verbose_name='Seminare: Titel'),
        ),
    ]
