# Generated by Django 3.2.3 on 2021-06-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_auto_20210617_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='form_successtext',
            field=models.TextField(blank=True, verbose_name='Formular // Erfolg Text'),
        ),
    ]
