# Generated by Django 3.1.6 on 2021-02-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50, verbose_name='Kunde')),
                ('testimonial', models.TextField(verbose_name='Rezension')),
                ('company', models.CharField(max_length=50, verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Referenz',
                'verbose_name_plural': 'Referenzen',
                'ordering': ['customer'],
            },
        ),
    ]
