# Generated by Django 3.1.6 on 2021-03-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210224_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, max_length=50, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='customer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kunde'),
        ),
    ]
