# Generated by Django 3.1.6 on 2021-03-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210304_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['testimonial'], 'verbose_name': 'Referenz', 'verbose_name_plural': 'Referenzen'},
        ),
    ]
